include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    avoid_init_to_null: ignore
    constant_identifier_names: ignore
    included_file_warning: ignore
    non_constant_identifier_names: ignore

linter:
  rules:
    # Personal preference. I don't find it more readable
    cascade_invocations: false

    # Conflicts with `prefer_single_quotes`
    # Single quotes are easier to type and don't compromise on readability.
    prefer_double_quotes: false

    # Incompatible with `prefer_final_locals`
    # Having immutable local variables makes larger functions more predictible
    # so we will use `prefer_final_locals` instead.
    unnecessary_final: false

    # Not quite suitable for Flutter, which may have a `build` method with a single
    # return, but that return is still complex enough that a "body" is worth it.
    prefer_expression_function_bodies: false

    # Conflicts with the convention used by flutter, which puts `Key key`
    # and `@required Widget child` last.
    always_put_required_named_parameters_first: false

    # There are situations where we voluntarily want to catch everything,
    # especially as a library.
    avoid_catches_without_on_clauses: false

    # Boring as it sometimes force a line of 81 characters to be split in two.
    # As long as we try to respect that 80 characters limit, going slightly
    # above is fine.
    lines_longer_than_80_chars: false

    # Conflicts with disabling `implicit-dynamic`
    avoid_annotating_with_dynamic: false

    # conflicts with `prefer_relative_imports`
    always_use_package_imports: false

    # False positive, null checks don't need a message
    prefer_asserts_with_message: false

    # Cumbersome with `context.select`
    avoid_types_on_closure_parameters: false

    # Too many false positive (builders)
    diagnostic_describe_all_properties: false

    # false positives (setter-like functions)
    avoid_positional_boolean_parameters: false

    # Does not apply to providers
    prefer_const_constructors_in_immutables: false

    hash_and_equals: true
    implicit_reopen: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_web_libraries_in_flutter: true
    avoid_type_to_string: true
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    avoid_dynamic_calls: true
    unnecessary_statements: true
    use_key_in_widget_constructors: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    use_string_buffers: true
    valid_regexps: true
    control_flow_in_finally: true
    always_specify_types: true
    # avoid_bool_literals_in_conditional_expressions: true
