name: flutter_quill_to_pdf
description: "Create PDF'S using deltas from Quill, with configurable attributes, fonts, and custom pdf widgets"
version: 2.0.0
homepage:
repository: https://github.com/CatHood0/flutter_quill_to_pdf/
issue_tracker: https://github.com/CatHood0/flutter_quill_to_pdf/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

topics: 
  - pdf
  - quill_delta
  - pdf_widgets
  - converter
  - pdf_converter

screenshots:
  - description: "Delta in editor"
    path: example/assets/delta_to_convert.jpg
  - description: "Delta converted in PDF"
    path: example/assets/delta_converted.jpg

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  dart_quill_delta: ^10.0.2
  flutter_quill_delta_easy_parser: ^1.0.2
  pdf: ^3.11.0
  universal_html: ^2.2.4
  cross_file: ^0.3.3+6
  html_unescape: ^2.0.0
  collection: ^1.16.0
  meta: ^1.12.0
  html: ^0.15.0
  path_provider: ^2.1.3
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test:
