name: quill_to_pdf
description: "Quill delta to PDF converter"
version: 1.0.0
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

  dart_quill_delta: ^9.3.18
  flutter_quill: ^9.3.18 
  pdf: ^3.10.8
  universal_html: ^2.2.4
  cross_file: ^0.3.3+6
  html_unescape: ^2.0.0
  collection: ^1.16.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

