name: flutter_quill_to_pdf
description: "Create PDF'S using deltas from Quill, with configurable attributes, fonts, and custom pdf widgets"
version: 2.3.9
homepage: https://github.com/CatHood0/flutter_quill_to_pdf
documentation: https://github.com/CatHood0/flutter_quill_to_pdf 
repository: https://github.com/CatHood0/flutter_quill_to_pdf
issue_tracker: https://github.com/CatHood0/flutter_quill_to_pdf/issues

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

topics: 
  - pdf
  - quill-delta
  - pdf-widgets
  - converter
  - pdf-converter

screenshots:
  - description: "Delta converted in PDF"
    path: assets/result_demo_to_pdf.png
  - description: "Delta in editor"
    path: assets/demo_to_pdf.png

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

dependencies:
  dart_quill_delta: ^10.8.3
  flutter_quill_delta_easy_parser: ^1.1.7
  highlight: ^0.7.0
  pdf: ^3.11.3
  collection: ^1.19.1
  path_provider: ^2.1.5
  dio: ^5.8.0
  meta: ^1.16.0
  numerus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test:

flutter:
  assets:
    - assets/
