name: Code Quality Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verify Flutter installation
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Perform Flutter Analysis
        run: flutter analyze

      - name: Preview Dart proposed changes
        run: dart fix --dry-run
